
-- Seed test properties in Conakry, Guinea
INSERT INTO properties (title, slug, description, price, currency, property_type, listing_type, city, district, address, surface, rooms, bathrooms, furnished, featured, published, status, published_at, latitude, longitude)
VALUES
  ('Villa moderne Kipé', 'villa-moderne-kipe', 'Superbe villa moderne avec piscine à Kipé, quartier résidentiel prisé de Conakry. 4 chambres, salon spacieux, cuisine américaine.', 850000000, 'GNF', 'villa', 'sale', 'Conakry', 'Kipé', 'Route de Kipé, Conakry', 350, 5, 3, true, true, true, 'published', now(), 9.5668, -13.6773),
  ('Appartement T3 Kaloum', 'appartement-t3-kaloum', 'Bel appartement T3 au centre-ville de Kaloum avec vue sur mer. Idéal pour professionnel ou couple.', 15000000, 'GNF', 'apartment', 'long_rental', 'Conakry', 'Kaloum', 'Avenue de la République, Kaloum', 85, 3, 1, true, false, true, 'published', now(), 9.5092, -13.7122),
  ('Studio meublé Ratoma', 'studio-meuble-ratoma', 'Studio entièrement meublé et équipé à Ratoma. Parfait pour séjour courte durée. WiFi, climatisation, parking.', 500000, 'GNF', 'studio', 'short_rental', 'Conakry', 'Ratoma', 'Carrefour Ratoma', 35, 1, 1, true, true, true, 'published', now(), 9.5833, -13.6333),
  ('Appartement T4 Dixinn', 'appartement-t4-dixinn', 'Grand appartement familial T4 à Dixinn, proche universités et ambassades. Terrasse avec vue panoramique.', 25000000, 'GNF', 'apartment', 'long_rental', 'Conakry', 'Dixinn', 'Route de Donka, Dixinn', 120, 4, 2, false, true, true, 'published', now(), 9.5350, -13.6680),
  ('Villa de standing Lambanyi', 'villa-standing-lambanyi', 'Villa haut de gamme à Lambanyi avec jardin, garage double, 5 chambres. Quartier calme et sécurisé.', 1200000000, 'GNF', 'villa', 'sale', 'Conakry', 'Lambanyi', 'Lambanyi, Ratoma', 420, 6, 4, true, false, true, 'published', now(), 9.6015, -13.6120),
  ('Terrain constructible Sonfonia', 'terrain-sonfonia', 'Terrain de 500 m² à Sonfonia, zone en plein développement. Titre foncier disponible.', 350000000, 'GNF', 'land', 'sale', 'Conakry', 'Sonfonia', 'Sonfonia Gare, Ratoma', 500, 0, 0, false, false, true, 'published', now(), 9.6200, -13.5980),
  ('Duplex meublé Cameroun', 'duplex-meuble-cameroun', 'Superbe duplex meublé au quartier Cameroun. 3 chambres, salon double, cuisine équipée. Idéal expatriés.', 20000000, 'GNF', 'apartment', 'long_rental', 'Conakry', 'Cameroun', 'Quartier Cameroun, Dixinn', 150, 3, 2, true, true, true, 'published', now(), 9.5280, -13.6850),
  ('Local commercial Madina', 'local-commercial-madina', 'Local commercial de 80 m² au marché Madina. Emplacement stratégique à fort passage.', 12000000, 'GNF', 'commercial', 'long_rental', 'Conakry', 'Madina', 'Marché Madina, Matam', 80, 2, 1, false, false, true, 'published', now(), 9.5350, -13.6950);
