// This file is automatically generated. Do not edit it directly.

import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL) {
  throw new Error(
    "VITE_SUPABASE_URL est manquant. Vérifie le fichier .env à la racine du projet.",
  );
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "VITE_SUPABASE_PUBLISHABLE_KEY est manquant. Vérifie le fichier .env à la racine du projet.",
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  },
);

/**
 * Diagnostic temporaire de la session Supabase.
 *
 * Permet de vérifier si le navigateur possède réellement
 * une session authentifiée.
 *
 * À supprimer ou désactiver une fois le problème RLS résolu.
 */
if (import.meta.env.DEV) {
  supabase.auth
    .getSession()
    .then(({ data, error }) => {
      if (error) {
        console.error(
          "[Supabase] Erreur lors de la récupération de la session :",
          error,
        );

        return;
      }

      if (!data.session) {
        console.warn(
          "[Supabase] Aucune session utilisateur active dans le navigateur.",
        );

        console.log("SUPABASE SESSION:", null);

        return;
      }

      console.log("SUPABASE SESSION:", data.session);

      console.log("SUPABASE USER:", {
        id: data.session.user.id,
        email: data.session.user.email,
        role: data.session.user.role,
      });
    })
    .catch((error) => {
      console.error(
        "[Supabase] Erreur inattendue pendant le diagnostic de session :",
        error,
      );
    });

  /**
   * Permet également de voir immédiatement les changements :
   * SIGNED_IN, SIGNED_OUT, TOKEN_REFRESHED, etc.
   */
  supabase.auth.onAuthStateChange((event, session) => {
    console.log("[Supabase Auth]", event);

    if (session?.user) {
      console.log("[Supabase Auth] Utilisateur :", {
        id: session.user.id,
        email: session.user.email,
      });
    } else {
      console.log("[Supabase Auth] Session :", null);
    }
  });
}
